alias ..='cd ..'
alias back='cd -'
alias ls='ls -FGh --color'
alias ll='ls -lA --color'
alias dir='ls -alg --color'
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'

export EDITOR=vim

# Colorful and informative command prompt;
# idea taken from a blog post by Steve Losh titled "Candy Colored Terminal".
D=$'\e[37;40m'
PINK=$'\e[35;40m'
GREEN=$'\e[32;40m'
ORANGE=$'\e[33;40m'
export PS1='${PINK}\u ${D}at ${ORANGE}\h ${D}in ${GREEN}\w${D}\n$ '
#export PS1='[\u@\h: \W] $ '
