alias ..='cd ..'
alias back='cd -'
alias ls='ls -FGh --color'
alias ll='ls -lA --color'
alias dir='ls -alg --color'
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'

export EDITOR=vim
export PS1='[\u@\h: \W] $ '
