set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"

PARENT="python:3.6.5-slim-stretch"

version=$(date +%Y%m%d)
NAME="$(cat "${thisdir}/name"):${version}"


echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'.
#
# DO NOT EDIT.

FROM ${PARENT}

USER root

EOF

cp -r $(dirname "${thisdir}")/dotfiles ${thisdir}/

cat "$(dirname "${thisdir}")/base.in" >> "${thisdir}/Dockerfile"
cat "$(dirname "${thisdir}")/nvim.in" >> "${thisdir}/Dockerfile"


echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"
rm -rf ${thisdir}/dotfiles
rm -f ${thisdir}/Dockerfile
echo ${version} > ${thisdir}/version


echo
python $(dirname "${thisdir}")/pyinstall.py \
    --cmd=py3 \
    --asroot \
    --dockercmd=python \
    --options="--rm -it"

