set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$(dirname "${thisdir}")"
parent_name=zppz/$(basename "${parentdir}")
parent_version=$(cat "$parentdir"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME=zppz/$(basename "${thisdir}"):"${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}
EOF

cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root


#--------------------------
# Python modeling packages

# lapack and gfortran are required by scipy and a couple others.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        liblapack3 \
        liblapack-dev \
        gfortran \
    \
    && pip install --no-cache-dir --upgrade \
        'scipy==0.17.1' \
    && pip install --no-cache-dir --upgrade \
        'cvxpy==0.4.2' \
        'patsy==0.4.1' \
        'scikit-learn==0.17.1' \
        'statsmodels==0.8.0rc1' \
    \
    && pip install --no-cache-dir --upgrade \
        'seaborn==0.7.1' \
    \
    && apt-get purge -y --auto-remove \
        build-essential \
        pkg-config \
        liblapack-dev \
        gfortran \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get autoremove -y \
    && apt-get clean


#-------------
# startup

USER ${USER}
WORKDIr ${HOME}

CMD ["python"]
EOF


echo
echo Creating image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"

