thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$(dirname "$thisdir")"
dockerdir="$(expr "$thisdir" : '\(.*/docker\).*')"

version=$(cat "$thisdir"/version)
parent_version=$(cat "$parentdir"/version)
if [[ "$version" < "$parent_version" ]]; then
    echo "$parent_version" > "$thisdir"/version
    version=$parent_version
fi

PARENT=zppz/$(basename "$parentdir"):"$parent_version"
NAME=zppz/$(basename "$thisdir"):"$version"

echo
echo =====================================================
echo Creating Dockerfile for $NAME
cat > "$thisdir"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}
EOF

cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root


#--------------------------
# Python data packages

# data stack

RUN pip install --no-cache-dir --upgrade \
        'numpy==1.11.0' \
        'sqlalchemy==1.0.13' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
    && pip install --no-cache-dir --upgrade \
        'pandas==0.18.1' \
    && apt-get purge -y --auto-remove \
        build-essential \
        pkg-config \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean


# plotting

# freetype and xft are required by matplotlib
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        libfreetype6 \
        libfreetype6-dev \
        libxft-dev \
    && pip install --no-cache-dir --upgrade \
        'matplotlib==1.5.1' \
        'bokeh==0.11.1' \
    && apt-get purge -y --auto-remove \
        build-essential \
        pkg-config \
        libfreetype6-dev \
        libxft-dev \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get autoremove -y \
    && apt-get clean


# HDF5

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        libhdf5-8 \
        libhdf5-dev \
        hdf5-tools \
    \
    && pip3 install --no-cache-dir --upgrade \
        'h5py==2.6.0' \
    \
    && apt-get purge -y --auto-remove \
        build-essential \
        pkg-config \
        libhdf5-dev \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean


#-------------
# startup

USER ${USER}
WORKDIr ${HOME}

CMD ["python"]
EOF


docker build -t "${NAME}" "${thisdir}"


