#!/bin/bash

set -Eeuo pipefail

TINY=zppz/tiny:21.01.02
TAG=$(docker run --rm ${TINY} make-date-version)
NAMESPACE=zppz
THISDIR=$(cd $( dirname "${BASH_SOURCE[0]}") && pwd )


function build-image {
    name="$1"
    shift
    build_dir="$1"
    shift
    echo
    echo "building $name ..."
    echo
    docker build -t "${name}" "${build_dir}" $@
    echo
}


function build-py3 {
    build-image ${NAMESPACE}/py3:${TAG} ${THISDIR}/py3
}


function build-py3-r {
    cmd="$(docker run --rm ${TINY} cat /usr/tools/find-image)"
    parent=$(bash -c "${cmd}" -- zppz/py3)
    build-image ${NAMESPACE}/py3-r:${TAG} ${THISDIR}/py3-r --build-arg PARENT=${parent}
}


function build-py3-rust {
    cmd="$(docker run --rm ${TINY} cat /usr/tools/find-image)"
    parent=$(bash -c "${cmd}" -- zppz/py3)
    build-image ${NAMESPACE}/py3-rust:${TAG} ${THISDIR}/py3-rust --build-arg PARENT=${parent}
}


function build-py3-build {
    cmd="$(docker run --rm ${TINY} cat /usr/tools/find-image)"
    parent=$(bash -c "${cmd}" -- zppz/py3)
    build-image ${NAMESPACE}/py3-build:${TAG} ${THISDIR}/py3-build --build-arg PARENT=${parent}
}


if [[ $# == 0 ]]; then
    img=py3
elif [[ $# == 1 ]]; then
    img="$1"
else
    >&2 echo "too many arguments"
    exit 1
fi

if [ "${img}" = py3 ]; then
    build-py3
elif [ "${img}" = py3-r ]; then
    build-py3-r
elif [ "${img}" = py3-rust ]; then
    build-py3-rust
elif [ "${img}" = py3-build ]; then
    build-py3-build
else
    >&2 echo "unknown image name '${img}'"
    exit 1
fi

