#!/usr/bin/bash


set -Eeuo pipefail

UBUNTU_VERSION=24.04
PYTHON_VERSION=3.12
PYTHON_TAG=312
# ubuntu 20.04 default python 3.8, 22.04 3.10, 24.04 3.12.


TAG=$(python3 -m minidocker make-date-version)
NAMESPACE=zppz
THISDIR=$(cd $( dirname "${BASH_SOURCE[0]}") && pwd )

>&2 echo
>&2 echo "Build machine info: $(uname -a)"
>&2 echo "Build machine kernel: $(uname -s)"
BUILDARCH=$(uname -p)
>&2 echo "Build machine arch: ${BUILDARCH}"
if [[ ${BUILDARCH} == arm && $(uname -s) == Darwin ]]; then
    TARGETARCH=arm64
else
    TARGETARCH=amd64
fi
# To test build AMD images on an Apple ARM machine, just set
# `TARGETARCH` to 'amd64'.

if [[ ${BUILDARCH} == arm && ${TARGETARCH} == amd64 ]]; then
    # https://stackoverflow.com/a/58225906
    # DOCKER_BUILDKIT=1
    # https://stackoverflow.com/a/64805337
    buildopts="buildx build --platform linux/amd64 --progress=plain --no-cache"
elif [[ ${BUILDARCH} != arm && ${TARGETARCH} == arm64 ]]; then
    >&2 echo "building for target ${TARGETARCH} on an ${BUILDARCH} machine is not supported"
    exit 1
else
    buildopts="build --progress=plain --no-cache"
fi


set -x


function build-image {
    name="$1"
    shift
    build_dir="$1"
    shift
    echo
    echo "building $name ..."
    echo
    docker ${buildopts} -t "${name}" "${build_dir}" $@
    echo
}


function build-py3 {
    build-image ${NAMESPACE}/py${PYTHON_TAG}:${TAG} ${THISDIR}/py3 --build-arg PARENT=ubuntu:${UBUNTU_VERSION} --build-arg PYTHON_VERSION=${PYTHON_VERSION}
}


function build-py3-r {
    parent=$(python3 -m minidocker find-image zppz/py${PYTHON_TAG})
    build-image ${NAMESPACE}/py${PYTHON_TAG}-r:${TAG} ${THISDIR}/py3-r --build-arg PARENT=${parent}
}


function build-py3-rust {
    parent=$(python3 -m minidocker find-image zppz/py${PYTHON_TAG})
    build-image ${NAMESPACE}/py${PYTHON_TAG}-rust:${TAG} ${THISDIR}/py3-rust --build-arg PARENT=${parent}
}


if [[ $# == 0 ]]; then
    img=py3
elif [[ $# == 1 ]]; then
    img="$1"
else
    >&2 echo "too many arguments"
    exit 1
fi

if [ "${img}" = py3 ]; then
    build-py3
elif [ "${img}" = py3-r ]; then
    build-py3-r
elif [ "${img}" = py3-rust ]; then
    build-py3-rust
else
    >&2 echo "unknown image name '${img}'"
    exit 1
fi


# Use `docker push zppz/py310:xxxxxx` to push the image to Dockerhub.
