set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        cmake \
        gcc \
        g++ \
        libc6-dev \
    && pip install --no-cache-dir --upgrade \
        'cffi==1.10.0' \
        'cython==0.26' \
        'easycython==1.0.7' \
        'pybind11==2.1.1' \
    && apt-get purge -y --auto-remove \
        cmake \
    && rm -rf /var/lib/apt/lists/* /tmp/*

# `cmake` is required to build `pybind11` tests.
# `pybind11` header files are stored in /usr/local/include/python3.5m/pybind11/

# Both `numba` and `cython` are often used with `numpy`,
# so we provide `numpy` for experimentation.

ENV LLVM_VERSION=4.0

#RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv 15CF4D18AF4F7421 \
RUN curl -skL --retry 3 http://apt.llvm.org/llvm-snapshot.gpg.key \
        | apt-key add - \
    && echo "deb http://apt.llvm.org/jessie/ llvm-toolchain-jessie-${LLVM_VERSION} main" > /etc/apt/sources.list.d/llvm.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libllvm-${LLVM_VERSION} llvm-${LLVM_VERSION}-dev \
    && rm -rf /var/lib/apt/lists/* \
    && export LLVM_CONFIG=/usr/lib/llvm-${LLVM_VERSION}/bin/llvm-config \
    && pip install --no-cache-dir --upgrade \
        'llvmlite==0.19.0' \
        'numba==0.34.0' \
        'numpy==1.13.1'
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


