set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

RUN pip install --no-cache-dir --upgrade \
        'cython==0.27.3' \
        'easycython==1.0.7' \
        'cffi==1.11.4' \
        'pybind11==2.2.2'

# `pybind11` header files are stored in /usr/local/include/python3.5m/pybind11/

# Have had issues with installing LLVM.
#
# Refer to this page:
#   https://apt.llvm.org
#
# This post may be informative:
#  https://solarianprogrammer.com/2017/12/14/clang-in-docker-container-cpp-17-development/
#
# This page lists downloads, including prebuilt binaries (5.0.1 has debian; earlier versions do not):
#  http://releases.llvm.org/download.html
#
# This page might be useful as well:
#  https://llvm.org/docs/Docker.html

ENV LLVM_VERSION 5.0
ENV LLVM_DESKTOP jessie

# This line used to be useful, but not any more.
#RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv 15CF4D18AF4F7421 \

RUN curl -skL --retry 3 http://apt.llvm.org/llvm-snapshot.gpg.key \
        | apt-key add - \
    && echo "deb http://apt.llvm.org/${LLVM_DESKTOP}/ llvm-toolchain-${LLVM_DESKTOP}-${LLVM_VERSION} main" > /etc/apt/sources.list.d/llvm.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libllvm${LLVM_VERSION} \
        llvm-${LLVM_VERSION} \
        llvm-${LLVM_VERSION}-dev \
        clang-format-${LLVM_VERSION} \
        valgrind \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/clang-format-${LLVM_VERSION} /usr/bin/clang-format \
    && curl --retry 3 https://github.com/catchorg/Catch2/releases/download/v2.1.2/catch.hpp > /usr/local/include/catch.hpp \
    && export LLVM_CONFIG=/usr/lib/llvm-${LLVM_VERSION}/bin/llvm-config \
    \
    && pip install --no-cache-dir --upgrade \
        'llvmlite==0.21.0' \
        'numba==0.36.2'
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


