thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$( dirname "$thisdir")"
dockerdir="$parentdir"

source "$dockerdir"/util.sh

TAG=$(find_version "$thisdir")
PARENT="debian:jessie"
NAME=$(basename "$thisdir"):"$TAG"
CHILDREN=()

echo
echo =====================================================
echo Creating Dockerfile for $NAME
cat > "$thisdir"/Dockerfile <<EOF
#==========================================================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#==========================================================

FROM ${PARENT}
EOF

cat >> "$thisdir"/Dockerfile <<'EOF'

USER root


#------------------
# group and user

ENV GROUP=docker-users
ENV USER=docker-user
ENV HOME=/home/${USER}

RUN groupadd --gid 1000 $GROUP \
    && mkdir -p ${HOME} \
    && useradd --uid 1000 --gid ${GROUP} --no-user-group --home ${HOME} --shell /bin/bash ${USER} \
    && chown -R ${USER}:${GROUP} ${HOME}


#----------------------
# System and basic

# 'curl': about 15 MB.
# 'locales': about 16MB.

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-utils \
        curl \
        less \
        locales \
        vim \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean


#----------------------
# Locale
#   default is C.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.en
ENV LC_ALL en_US.UTF-8

RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && /usr/sbin/update-locale LANG=en_US.UTF-8


#--------------------
# bash customization

COPY dotfiles/bashrc /etc/bash.bashrc

RUN chmod +r /etc/bash.bashrc

ENV SHELL=/bin/bash


#--------------------
# vim customization

COPY dotfiles/vimrc /etc/vim/vimrc.local
COPY dotfiles/vim/ /etc/vim/

RUN chmod -R +rX /etc/vim


#--------------
# latex

RUN apt-get update \
    && apt-get install -y \
        texlive-full \
        texlive-fonts-recommended \
        texlive-fonts-extra \
        texlive-latex-base \
        texlive-latex-extra \
        texlive-latex-recommended \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean

RUN cd /tmp \
    && curl -sL https://github.com/zpz/latex/archive/master.tar.gz -o - |tar xz \
    && cp latex-master/bin/* /usr/local/bin \
    && chmod +x /usr/local/bin/* \
    && rm -rf /tmp/*

CMD ["/bin/bash"]

USER ${USER}
WORKDIR ${HOME}
EOF


cp -rf "$parentdir"/dotfiles "$thisdir"/
build_image "$thisdir" "$NAME" "${CHILDREN[@]}"
retval=$?
rm -rf "$thisdir"/dotfiles

if [[ $retval == 0 ]]; then
    build_children "$thisdir" "${CHILDREN[@]}"
else
    false
fi

