thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$( dirname "${thisdir}")"

version=$(cat "${thisdir}"/version)
parent_version=$(cat "${parentdir}/version")
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}/version"
    version=${parent_version}
fi

PARENT=zppz/$(basename "${parentdir}"):"${parent_version}"
NAME=zppz/$(basename "${thisdir}"):"${version}"

echo
echo =====================================================
echo Creating Dockerfile for ${NAME}
cat > "${thisdir}/Dockerfile" <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}

EOF
cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root


#--------------
# latex

# textlive-latex-extra provides 'lastpage', among others.

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        texlive-base \
        texlive-fonts-recommended \
        texlive-latex-base \
        texlive-latex-extra \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean


COPY ./bin/ /usr/local/bin/
COPY ./sty/ /usr/local/share/texmf/tex/latex/zz/
RUN chmod +x /usr/local/bin/* \
    && texhash


# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         build-essential \
#     && curl -sL http://ftp.math.utah.edu/pub/bibclean/bibclean-2.17.tar.gz -o - |tar xz -C /tmp/ \
#     && (cd /tmp/bibclean-2.17 && ./configure && make all check install) \
#     && curl -sL http://ftp.math.utah.edu/pub/bibparse/bibparse-1.11.tar.gz -o - |tar xz -C /tmp/ \
#     && (cd /tmp/bibparse-1.11 && ./configure && make all check install) \
#     && curl -sL http://ftp.math.utah.edu/pub/biblabel/biblabel-0.09.tar.gz -o - |tar xz -C /tmp/ \
#     && (cd /tmp/biblabel-0.09 && ./configure && make all check install ) \
#     && curl -sL http://ftp.math.utah.edu/pub/biborder/biborder-0.17.tar.gz -o - |tar xz -C /tmp/ \
#     && (cd /tmp/biborder-0.17 && ./configure && make all check install ) \
#     && apt-get purge -y --auto-remove \
#         build-essential \
#     && rm -rf /var/lib/apt/lists/* \
#     && apt-get -y autoremove \
#     && apt-get clean
#     \
#     && curl -sL https://github.com/zpz/latex/archive/master.tar.gz -o - |tar xz -C /tmp/ \
#     && cp /tmp/latex-master/bin/* /usr/local/bin \
#     && mv /tmp/latex-master/sty /usr/share/texmf/tex/latex/zz \
#     && chmod +x /usr/local/bin/* \
#     && rm -rf /tmp/*


#-----------
# startup

USER ${USER}
WORKDIR ${HOME}

CMD ["/bin/bash"]
EOF

echo
echo Building image "'${NAME}'"
echo
curl -sL https://github.com/zpz/latex/archive/master.tar.gz -o - |tar xz -C /tmp/
mv /tmp/latex-master/bin "${thisdir}"/bin
mv /tmp/latex-master/sty "${thisdir}"/sty
docker build -t "${NAME}" "${thisdir}"
rm -rf "${thisdir}"/bin "${thisdir}/sty"
rm -rf /tmp/latex-master

