thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$( dirname "${thisdir}")"

version=$(cat "${thisdir}"/version)
parent_version=$(cat "${parentdir}/version")
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}/version"
    version=${parent_version}
fi

PARENT=zppz/$(basename "${parentdir}"):"${parent_version}"
NAME=zppz/$(basename "${thisdir}"):"${version}"

echo
echo =====================================================
echo Creating Dockerfile for ${NAME}
cat > "${thisdir}/Dockerfile" <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}

EOF
cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root


#--------------
# latex

# textlive-latex-extra provides 'lastpage', among others.

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        texlive-base \
        texlive-fonts-recommended \
        texlive-latex-base \
        texlive-latex-extra \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean

COPY ./bin/ /usr/local/bin/
RUN chmod +x /usr/local/bin/*


#-----------
# startup

USER ${USER}
WORKDIR ${HOME}

CMD ["/bin/bash"]
EOF

echo
echo Building image "'${NAME}'"
echo
curl -sL https://github.com/zpz/latex/archive/master.tar.gz -o - |tar xz -C /tmp/
mv /tmp/latex-master/bin "${thisdir}"/bin
docker build -t "${NAME}" "${thisdir}"
rm -rf "${thisdir}"/bin /tmp/latex-master

