set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

RUN pip install --no-cache-dir --upgrade \
        'numpy==1.13.0' \
        'pandas==0.20.2' \
        'pyarrow==0.4.1' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        liblapack3 liblapack-dev \
    && pip install --no-cache-dir --upgrade \
        'scipy==0.19.0' \
    && apt-get install -y --no-install-recommends \
        g++ \
        gfortran \
    && pip install --no-cache-dir --upgrade \
        'cvxpy==0.4.10' \
    && apt-get purge -y --auto-remove \
        g++ \
        gfortran \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && pip install --no-cache-dir --upgrade \
        'scikit-learn==0.18.1' \
        'patsy==0.4.1' \
        'statsmodels==0.8.0'
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


