set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        graphviz \
        gcc \
        make \
        libc6-dev \
    && pip install --no-cache-dir --upgrade \
        'bokeh==0.12.15' \
        'dask==0.17.2' \
        'dask-avro==0.2.0' \
        'dask-ml==0.4.1' \
        'distributed==1.21.4' \
        'graphviz==0.8.2' \
        'pandas==0.22.0' \
        'scikit-learn==0.19.1' \
        'toolz==0.9.0' \
    && apt-get remove --purge -y \
        gcc make libc6-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


