#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import re
import sys

sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])

# Make ptpython command history persistent across
# Docker sessions.
os.environ['XDG_CONFIG_HOME'] = '/etc/xdg'
os.environ['XDG_DATA_HOME'] = os.environ.get('TMPDIR', '/tmp')

from ptpython.entry_points.run_ptpython import run

sys.exit(run())
