set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(date +%Y%m%d)
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

RUN pip install --no-cache-dir --upgrade \
        'bokeh==0.12.15' \
        'dask==0.17.2' \
        'dask-avro==0.2.0' \
        'dask-ml==0.4.1' \
        'graphviz==0.8.2' \
        'h5py==2.7.1' \
        'pandas==0.22.0' \
        'partd==0.3.8' \
        'scikit-learn==0.19.1' \
        'statsmodels==0.8.0' \
        'toolz==0.9.0'

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        graphviz \
        gcc \
        make \
        libc6-dev \
    && pip install --no-cache-dir --upgrade \
        'distributed==1.21.4' \
        'graphviz==0.8.2' \
    && apt-get remove --purge -y \
        gcc make libc6-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"
rm -f ${thisdir}/Dockerfile
echo ${version} > ${thisdir}/version

echo
python ../../../pyinstall.py \
    --cmd=dask \
    --dockercmd=ptpython \
    --options="-it --rm"


