set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$(dirname "${thisdir}")"
parent_name=zppz/$(basename "${parentdir}")
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}:${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME=zppz/$(basename "${thisdir}"):"${version}"


echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}
EOF

cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root
WORKDIR /

# 'graphviz' and 'make' are to be used with Sphinx.

RUN pip install --no-cache-dir --upgrade \
        'ipython==5.0.0' \
        'ipdb==0.10.1' \
        'pudb==2016.2' \
        'pylint==1.6.4' \
        'pytest==2.9.2' \
        'pytest-cov==2.3.0' \
        'requests==2.10.0' \
        'sh==1.11' \
        'toolz==0.8.0' \
        'yapf==0.11.0' \
    && ln -s /usr/local/bin/py.test /usr/local/bin/pytest \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && pip install --no-cache-dir --upgrade \
        'line_profiler==1.0' \
    && apt-get install -y --no-install-recommends \
        graphviz \
        make \
    && pip install --no-cache-dir --upgrade \
        'Sphinx==1.4.5' \
        'sphinx_rtd_theme==0.1.9' \
    && apt-get purge -y --auto-remove \
        build-essential \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean

CMD ["python"]
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"

