set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'

# This is a catch-all image for learning purposes.

#=============================
# Generated by 'build.sh'
#
# DO NOT EDIT.
#=============================

FROM ${PARENT}
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

USER root
WORKDIR /

# freetype and xft are required by matplotlib

RUN pip install --no-cache-dir --upgrade \
        'bokeh>=0.12.4' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libfreetype6 \
        libfreetype6-dev \
        libxft-dev \
    && pip install --no-cache-dir --upgrade \
        'matplotlib>=2.0.0' \
        'seaborn>=0.7.1' \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get autoremove -y \
    && apt-get clean -y

RUN pip install --no-cache-dir --upgrade \
        'pandas==0.19.2' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        liblapack3 liblapack-dev \
    && pip install --no-cache-dir --upgrade \
        'scipy==0.19.0' \
    && apt-get install -y --no-install-recommends \
        g++ \
        gfortran \
    && pip install --no-cache-dir --upgrade \
        'cvxpy==0.4.9' \
    && apt-get purge -y --auto-remove \
        g++ \
        gfortran \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get autoremove -y \
    && apt-get clean -y

RUN pip install --no-cache-dir --upgrade \
        'scikit-learn==0.18.1' \
        'patsy==0.4.1' \
        'statsmodels==0.8.0'

CMD ["/bin/bash"]
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


