set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$(dirname "${thisdir}")"
parent_name=zppz/$(basename "${parentdir}")
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME=zppz/$(basename "${thisdir}"):"${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}
EOF

cat >> "${thisdir}/Dockerfile" <<'EOF'

USER root


#--------------------------
# Python data packages

# freetype and xft are required by matplotlib.
# bokeh installs tornado.

RUN pip install --no-cache-dir --upgrade \
        'numpy==1.11.0' \
        'sqlalchemy==1.0.13' \
        'sqlparse==0.1.19' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
    && pip install --no-cache-dir --upgrade \
        'pandas==0.18.1' \
    && apt-get install -y --no-install-recommends \
        libfreetype6 \
        libfreetype6-dev \
        libxft-dev \
    && pip install --no-cache-dir --upgrade \
        'matplotlib==1.5.1' \
        'bokeh==0.12.0' \
    && apt-get purge -y --auto-remove \
        build-essential \
        pkg-config \
        libfreetype6-dev \
        libxft-dev \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean


# # HDF5
# 
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         build-essential \
#         pkg-config \
#         libhdf5-8 \
#         libhdf5-dev \
#         hdf5-tools \
#     \
#     && pip3 install --no-cache-dir --upgrade \
#         'h5py==2.6.0' \
#     \
#     && apt-get purge -y --auto-remove \
#         build-essential \
#         pkg-config \
#         libhdf5-dev \
#     && rm -rf /var/lib/apt/lists/* /tmp/* \
#     && apt-get -y autoremove \
#     && apt-get clean
# 

#-------------
# startup

USER ${USER}
WORKDIR ${HOME}

CMD ["python"]
EOF


echo
echo Creating image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


