set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    version="${parent_version}"
    echo "${version}" > "${thisdir}"/version
fi
NAME="$(cat "${thisdir}/name"):${version}"


echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'.
# Generated by 'build.sh'.
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "$thisdir"/Dockerfile <<'EOF'

RUN pip install --no-cache-dir --upgrade \
        PyMySQL==0.7.11
EOF

echo
echo building image "'${NAME}'"...
echo
docker build -t "${NAME}" "${thisdir}"



