set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"
parentdir="$(dirname "${thisdir}")"
parent_name="$(cat "${parentdir}/name")"
parent_version="$(cat "${parentdir}/version")"
PARENT="${parent_name}":"${parent_version}"

version=$(date +%Y%m%d)
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for $NAME
cat > "${thisdir}/Dockerfile" <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'.
#
# DO NOT EDIT.

# In the intended use cases of this image,
# Python is the primary deveopment environment,
# whereas R is called from Python to make use of certain
# specialized R packages.
#
# One-way Python/R inter-op, namely calling R from Python,
# is provisioned by the Python package 'rpy2'.

# For instructions on installing R, go to
#   https://cloud.r-project.org
#   click 'Download R for Linux'
#   then click 'debian'
#
# The direct URL seems to be
#   https://cran.r-project.org/bin/linux/debian/
#
# How to install R from a custom server:
# 1. add source to '/etc/apt/sources.list' by 'echo .. >> '.
# 2. apt-get update
#       this should fail with error 'NO_PUBKEY xyz'
# 3. get key by
#       'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys xyz'
# 4. apt-get-update
#       this should succeed
# 5. get R version number by 'apt-cache show r-base'
# 6. specify version number in 'apt-get install'


FROM ${PARENT}
USER root
EOF


# For debian jessie:
#
#ENV R_BASE_VERSION 3.4.3-1
#RUN echo 'deb http://cran.rstudio.com/bin/linux/debian jessie-cran34/' >> /etc/apt/sources.list \
#    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FCAE2A0E115C3D8A \
#    && apt-get update \

# We no longer use the above because
# debian stretch has a reasonably recent R.

cat >> "${thisdir}/Dockerfile" <<'EOF'


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        r-base \
        r-base-dev \
    \
    && pip install --no-cache-dir --upgrade \
        'rpy2==2.9.2' \
    \
    && apt-get remove --purge -y \
        r-base-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

COPY ./install.r /usr/local/bin
COPY ./install.version.r /usr/local/bin

RUN chmod +x /usr/local/bin/install.r /usr/local/bin/install.version.r
RUN install.r versions

EOF


echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"
rm -f ${thisdir}/Dockerfile
echo ${version} > ${thisdir}/version

echo
python ../../../pyinstall.py \
    --cmd=py3r \
    --options="-it --rm"

