set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir="$( cd "$( dirname "${thisfile}" )" && pwd )"

PARENT="maven:3.5.0-jdk-8"
version=$(cat "${thisdir}"/version)
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for ${NAME}
cat > "${thisdir}/Dockerfile" <<EOF
# Dockerfile for image '${NAME}'

#===========================
# Generated by 'build.sh'.
#
# DO NOT EDIT.
#===========================

FROM ${PARENT}
EOF

cat "$(dirname "${thisdir}")/base.in" >> "${thisdir}/Dockerfile"

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"

