set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(date +%Y%m%d)
NAME="$(cat "${thisdir}/name"):${version}"


echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'.
#
# DO NOT EDIT.

FROM ${PARENT}

USER root

EOF

cp -r ../../dotfiles ./

cat >> "${thisdir}/Dockerfile" <<'EOF'

# The section below installs important tools for Python development, such as
# documentation, testing, code analysis, code formatting,
# IPython, Jupyter Notebook.

# TODO:
# it is possible that this config file is not loaded by Jupyter Notebook.
ENV JUPYTER_CONFIG_DIR=/etc/xdg/jupyter/
COPY dotfiles/ipython/ipython_config.py /etc/xdg/ipython/profile_default/
COPY dotfiles/jupyter/jupyter_notebook_config.py ${JUPYTER_CONFIG_DIR}
COPY dotfiles/ptpython/config.py /home/docker-user/.ptpython/

RUN pip install --no-cache-dir --upgrade \
        'coverage' \
        'mypy' \
        'ptpython' \
        'pylint' \
        'pytest' \
        'Sphinx' \
        'yapf' \
    && pip install --no-cache-dir --upgrade \
        'ipython' \
        'notebook' \
        'jupyterlab' \
    && chmod +r /etc/xdg/ipython/profile_default/ipython_config.py \
    && chown -R docker-user /home/docker-user/.ptpython \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        graphviz \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

# Use `yapf` to format Python code in-pace:
#   yapf -ir -vv --no-local-style .

# `notebook` requires (and will install if not available) ipython, pyzmq, tornado, jinja2 and some other things.

# `graphviz` is required by `Sphinx` to generate some graphs such as class hierarchy diagrams.

# Other useful packages:
#    boltons
#    Faker
#    flake8
#    ipdb
#    pudb
#    pyflakes
#    radon

EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"
rm -rf dotfiles
rm -f ${thisdir}/Dockerfile
echo ${version} > ${thisdir}/version

echo
python ../../pyinstall.py \
    --cmd=py3dev  \
    --pypath=src/github-zpz/utilities.py \
    --dockercmd=/bin/bash \
    --options="--rm -it"

