set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    echo "${parent_version}" > "${thisdir}"/version
    version=${parent_version}
fi
NAME="$(cat "${thisdir}/name"):${version}"

echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'
# Generated by 'build.sh'
#
# DO NOT EDIT.

FROM ${PARENT}
USER root
EOF

cat >> "${thisdir}"/Dockerfile <<'EOF'

# It is my opinion that starting now, in September 2017,
# we can just use Bokeh and forget about Matplotlib.

# freetype and xft are required by matplotlib
#RUN apt-get update \
#    && apt-get install -y --no-install-recommends \
#        libfreetype6 \
#        libfreetype6-dev \
#        libxft-dev \
#        tcl \
#        tk \
#    && pip install --no-cache-dir --upgrade \
#        'matplotlib==2.1.0' \
#        'seaborn==0.8.1' \
#    && apt-get purge -y --auto-remove \
#        libfreetype6-dev \
#        libxft-dev \
#    && rm -rf /var/lib/apt/lists/* /tmp/*

RUN pip install --no-cache-dir --upgrade \
        'bokeh==0.12.13' \
        'param==1.5.1' \
        'plotly==2.2.3' \
    && pip install --no-cache-dir --upgrade \
        'holoviews==1.9.2'

# 'gif' support in Holoviews requires ImageMagick
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        imagemagick \
    && rm -rf /var/lib/apt/lists/* /tmp/*
EOF

echo
echo Building image "'${NAME}'"
echo
docker build -t "${NAME}" "${thisdir}"


