set -o nounset
set -o pipefail

thisfile="${BASH_SOURCE[0]}"
thisdir=$( cd "$( dirname "${thisfile}" )" && pwd )
parentdir=$(dirname "${thisdir}")
parent_name=$(cat "${parentdir}"/name)
parent_version=$(cat "${parentdir}"/version)
PARENT="${parent_name}":"${parent_version}"

version=$(cat "${thisdir}"/version)
if [[ "${version}" < "${parent_version}" ]]; then
    version="${parent_version}"
    echo "${version}" > "${thisdir}"/version
fi
NAME="$(cat "${thisdir}/name"):${version}"


echo
echo =====================================================
echo Creating Dockerfile for "'${NAME}'"...
cat > "${thisdir}"/Dockerfile <<EOF
# Dockerfile for image '${NAME}'.
# Generated by 'build.sh'.
#
# DO NOT EDIT.

FROM ${PARENT}
EOF

cat >> "$thisdir"/Dockerfile <<'EOF'

USER root
WORKDIR /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libpq5 \
        libpq-dev \
    && pip install --no-cache-dir --upgrade \
        'psycopg2==2.7.1' \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && apt-get -y autoremove \
    && apt-get clean

RUN pip install --no-cache-dir --upgrade \
        'aiohttp==1.3.5' \
        'asyncpg==0.9.0' \
        'uvloop==0.8.0'

CMD ["/bin/bash"]
EOF

echo
echo building image "'${NAME}'"...
echo
docker build -t "${NAME}" "${thisdir}"



